apiVersion: apps/v1
kind: Deployment
metadata:
  name: graduation
  namespace: ivolve
  labels:
    app: ivolve
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ivolve
  template:
    metadata:
      labels:
        app: ivolve
    spec:
      containers:
      - name: ivolve-nti
        image: 140592727911.dkr.ecr.eu-central-1.amazonaws.com/finalproject-ivolve-repo:0.0.1
        ports:
        - containerPort: 5000